include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    artifact-name: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
    artifact-name: totem_right
# there is no settingsreset (needed) for the XIAO
